import { useInsight } from '../hooks/useInsight'

/**
 * Warm weekly "household coach" line generated by Claude server-side.
 * Renders nothing until an insight exists (and never in local mode).
 * Visual styling is intentionally minimal until the design pass.
 */
export function WeeklyInsightCard() {
  const { insight } = useInsight()
  if (!insight) return null

  return (
    <div className="mb-3 rounded-2xl bg-brand-50 px-4 py-3 text-sm text-brand-700 shadow-sm">
      <div className="mb-1 flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-wide text-brand-600">
        <span>💛</span> This week
      </div>
      <p className="leading-snug">{insight.text}</p>
    </div>
  )
}
