// Shared domain types for Homebase.

export type Owner = 'Meg' | 'Leti' | 'Both'

export type Frequency =
  | 'Daily'
  | 'Weekly'
  | 'Bi-Weekly'
  | 'Monthly'
  | 'Quarterly'
  | 'Seasonal'
  | 'As needed'
  | 'Ongoing'

export type MemberName = 'Meg' | 'Leti'

export interface Member {
  name: MemberName
  color: string
}

export interface ChoreCategory {
  id: string
  name: string
  sortOrder: number
}

export interface Chore {
  id: string
  categoryId: string
  name: string
  frequency: Frequency
  owner: Owner
  done: boolean
  /** ISO timestamp of when it was last marked done, or null if never. */
  lastDoneAt: string | null
  sortOrder: number
  /** When true, a push reminder fires (to the owner) once this chore is due. */
  reminderEnabled: boolean
  /** Local time-of-day 'HH:MM' to remind at, or null to use the household default. */
  reminderTime: string | null
}

/** A cached weekly "household coach" line, generated by Claude server-side. */
export interface Insight {
  /** ISO date (Monday) identifying the week this insight covers. */
  weekStart: string
  text: string
  createdAt: string
}
